### ISSUE TITLE
Flappy Birds is too hard

### ISSUE THREAD

**Issue by soegaard** [vishesh/racketscript-playground#15]
Flappy Birds is too hard. Ironic I know, but I doubt anyone can score even a single point!

**Comment by vishesh** [comment]
Haha. I can get upto 4 points. Could this be due to different browser/machine/random game?

**Comment by soegaard** [comment]
Oh - it could be the browser. I use Chrome on OS X.
On the other hand I might be out of practise.

**Comment by stchang** [comment]
Practice more.
