### ISSUE TITLE
Running locally does not work

### ISSUE THREAD

**Issue by pmatos** [vishesh/racketscript-playground#16]
I have installed the playground locally under racket 6.12, loaded factorial example and pressed 'compile + run'. Compile looks fine but nothing is ran. Nothing in output window or in log window. 

What's the best way to further understand what's happening?

**Comment by vishesh** [comment]
Hi @pmatos ,

Sorry about late response. RacketScript playground is bit outdated (its a bit hacky) and build is broken.  I didn't get chance to look into this, but I will probably look over this weekend. I think the best bet right now is is to use the RacketScript CLI directly. Let me know if that doesn't work either.

**Comment by vishesh** [comment]
@pmatos: I think you did check log window, but can you please check if there is anything in the browser console log again? There must be something there. Also can you show the snippet of program you wrote. Could be some issue with `print` as we did bunch of updates around that and ports.

**Comment by vishesh** [comment]
Should be fixed by https://github.com/vishesh/racketscript-playground/pull/18 and https://github.com/vishesh/racketscript/pull/222.

https://github.com/vishesh/racketscript-playground/pull/19 should make it just a docker run.
