### ISSUE TITLE
DOM loaded twice

### ISSUE THREAD

**Issue by soegaard** [vishesh/racketscript-playground#7]
The Hello message is added twice.

This is on an iPad using Google Chrome (using WebKit if I recall correctly). 

![img_0050](https://user-images.githubusercontent.com/461765/27952158-9f5351a4-6307-11e7-8d6c-67cf89881b4e.PNG)

**Comment by rhencke** [comment]
This also occurs on Chrome.

**Comment by vishesh** [comment]
Looks like I un-watched this repo by mistake. Thanks @soegaard  and @rhencke  for reporting. @glebm  Thanks for fixing this!
